require "rake/clean"

SOURCE_FILES = FileList["{,fa/,regex/}*.swift"]

file "finite-automata" => SOURCE_FILES do |t|
  sh "xcrun -sdk macosx swiftc -o #{t.name} -- #{t.sources.join(" ")}"
end
CLEAN.include("finite-automata")

task :run => "finite-automata" do |t|
  exec "./#{t.source}"
end

task :default => :run
