require "rake/clean"

BUILT_FRAMEWORKS_DIR = "Carthage.build/Mac"

file "finite-automata" => FileList["{,fa/}*.swift"] do |t|
  sh "xcrun -sdk macosx swiftc -o #{t.name} " \
     "-F#{BUILT_FRAMEWORKS_DIR} -Xlinker -rpath -Xlinker #{BUILT_FRAMEWORKS_DIR} " \
      "-- #{t.sources.join(" ")}"
end
CLEAN.include("finite-automata")

task :run => "finite-automata" do |t|
  exec "./#{t.source}"
end

task :default => :run
