var tape = Tape(["1", "2", "3", "4"], "5", [], "_")
println(tape)
tape.moveLeft()
println(tape)
tape.moveLeft()
println(tape)
tape.moveLeft()
println(tape)
tape.moveLeft()
println(tape)
tape.moveLeft()
println(tape)
tape.moveLeft()
println(tape)
for _ in 1...10 {
    tape.moveRight()
}
println(tape)
