var tape = Tape(["1", "2", "3", "4"], "5", [], "_")
println(tape)
tape.move(.Left)
println(tape)
tape.move(.Left)
println(tape)
tape.move(.Left)
println(tape)
tape.move(.Left)
println(tape)
tape.move(.Left)
println(tape)
tape.move(.Left)
println(tape)
for _ in 1...10 {
    tape.move(.Right)
}
println(tape)
