require "rake/clean"

file "dtm" => FileList["*.swift"] do |t|
  sh "xcrun -sdk macosx swiftc -o #{t.name} -- #{t.sources.join(" ")}"
end
CLEAN.include("dtm")

task :run => "dtm" do |t|
  exec "./#{t.source}"
end

task :default => :run
